from app.models.schemas import ModelInfo


def get_default_models() -> list[ModelInfo]:
    # NOTE: These are placeholder metadata for MVP.
    # You can update pricing/capabilities over time or let users manage their own.
    return [
        ModelInfo(
            id="gpt-4o-mini",
            name="GPT-4o mini",
            provider="openai",
            input_price_per_1k=0.15,
            output_price_per_1k=0.60,
            max_context_tokens=128000,
            speed_tier="fast",
            capability={
                "simple_qa": 0.70,
                "summarization": 0.75,
                "code_generation": 0.70,
                "creative_writing": 0.70,
                "analysis": 0.65,
                "math_reasoning": 0.60,
                "translation": 0.75,
                "conversation": 0.80,
                "extraction": 0.70,
            },
        ),
        ModelInfo(
            id="gpt-4o",
            name="GPT-4o",
            provider="openai",
            input_price_per_1k=5.0,
            output_price_per_1k=15.0,
            max_context_tokens=128000,
            speed_tier="medium",
            capability={
                "simple_qa": 0.90,
                "summarization": 0.90,
                "code_generation": 0.90,
                "creative_writing": 0.90,
                "analysis": 0.92,
                "math_reasoning": 0.92,
                "translation": 0.90,
                "conversation": 0.90,
                "extraction": 0.90,
            },
        ),
        ModelInfo(
            id="claude-3-5-sonnet",
            name="Claude 3.5 Sonnet",
            provider="anthropic",
            input_price_per_1k=3.0,
            output_price_per_1k=15.0,
            max_context_tokens=200000,
            speed_tier="medium",
            capability={
                "simple_qa": 0.90,
                "summarization": 0.92,
                "code_generation": 0.92,
                "creative_writing": 0.90,
                "analysis": 0.92,
                "math_reasoning": 0.90,
                "translation": 0.90,
                "conversation": 0.90,
                "extraction": 0.90,
            },
        ),
        ModelInfo(
            id="claude-3-haiku",
            name="Claude 3 Haiku",
            provider="anthropic",
            input_price_per_1k=0.25,
            output_price_per_1k=1.25,
            max_context_tokens=200000,
            speed_tier="fast",
            capability={
                "simple_qa": 0.72,
                "summarization": 0.75,
                "code_generation": 0.68,
                "creative_writing": 0.70,
                "analysis": 0.65,
                "math_reasoning": 0.60,
                "translation": 0.75,
                "conversation": 0.80,
                "extraction": 0.70,
            },
        ),
        ModelInfo(
            id="gemini-1-5-flash",
            name="Gemini 1.5 Flash",
            provider="google",
            input_price_per_1k=0.35,
            output_price_per_1k=1.05,
            max_context_tokens=1000000,
            speed_tier="fast",
            capability={
                "simple_qa": 0.75,
                "summarization": 0.78,
                "code_generation": 0.70,
                "creative_writing": 0.72,
                "analysis": 0.70,
                "math_reasoning": 0.65,
                "translation": 0.78,
                "conversation": 0.80,
                "extraction": 0.75,
            },
        ),
        ModelInfo(
            id="gemini-1-5-pro",
            name="Gemini 1.5 Pro",
            provider="google",
            input_price_per_1k=3.5,
            output_price_per_1k=10.5,
            max_context_tokens=1000000,
            speed_tier="medium",
            capability={
                "simple_qa": 0.90,
                "summarization": 0.90,
                "code_generation": 0.88,
                "creative_writing": 0.88,
                "analysis": 0.90,
                "math_reasoning": 0.88,
                "translation": 0.90,
                "conversation": 0.88,
                "extraction": 0.90,
            },
        ),
        ModelInfo(
            id="llama-3-70b",
            name="Llama 3 70B (hosted)",
            provider="meta",
            input_price_per_1k=0.9,
            output_price_per_1k=0.9,
            max_context_tokens=8192,
            speed_tier="slow",
            capability={
                "simple_qa": 0.78,
                "summarization": 0.78,
                "code_generation": 0.75,
                "creative_writing": 0.78,
                "analysis": 0.72,
                "math_reasoning": 0.70,
                "translation": 0.75,
                "conversation": 0.78,
                "extraction": 0.75,
            },
        ),
        ModelInfo(
            id="mistral-large",
            name="Mistral Large",
            provider="mistral",
            input_price_per_1k=2.0,
            output_price_per_1k=6.0,
            max_context_tokens=32000,
            speed_tier="medium",
            capability={
                "simple_qa": 0.86,
                "summarization": 0.86,
                "code_generation": 0.84,
                "creative_writing": 0.84,
                "analysis": 0.84,
                "math_reasoning": 0.82,
                "translation": 0.84,
                "conversation": 0.84,
                "extraction": 0.86,
            },
        ),
    ]
